export enum DnDClass {
  Artificer = "artificer",
  Barbarian = "barbarian",
  Bard = "bard",
  Cleric = "cleric",
  Druid = "druid",
  Fighter = "fighter",
  Monk = "monk",
  Paladin = "paladin",
  Ranger = "ranger",
  Rogue = "rogue",
  Sorcerer = "sorcerer",
  Warlock = "warlock",
  Wizard = "wizard"
}

export const DnDSubClass = {
  artificer: {
    alchemist: "alchemist",
    armorer: "armorer",
    artillerist: "artillerist",
    battleSmith: "aattle amith",
  },
  barbarian: {
    ancenstralGuardian: "ancenstral guardian",
    battlerager: "battlerager",
    beast: "beast",
    berserker: "berserker",
    stormHerald: "storm herald",
    totemWarriorBear: "totem warrior - bear",
    totemWarriorEagle: "totem warrior - eagle",
    totemWarriorElk: "totem tarrior - elk",
    totemWarriorTiger: "totem warrior - tiger",
    totemWarriorWolf: "totem warrior - wolf",
    wildMagic: "wild magic - barbarian",
    zealot: "zealot",
  },
  bard: {
    creation: "college of creation",
    eloquence: "college of eloquence",
    glamour: "college of glamour",
    lore: "college of lore",
    spirits: "college of spirits",
    swords: "college of swords",
    valor: "college of valor",
    whispers: "college of whispers",
  },
  cleric: {
    arcana: "arcana comain",
    death: "death domain",
    forge: "forge domain",
    grave: "grave domain",
    knowledge: "knowledge domain",
    life: "life domain",
    light: "light domain",
    nature: "nature domain",
    order: "order domain",
    peace: "peace domain",
    tempest: "tempest domain",
    trickery: "trickery domain",
    twilight: "twilight domain",
    war: "war domain",
  },
  druid: {
    dreams: "dircle of dreams",
    land: "circle of the land",
    shepherd: "cricle of the shepherd",
    spores: "cricle of spores",
    stars: "cricle of stars",
    twilight: "circle of twilight",
    wildfire: "circle of wildfire",
  },
  figher: {
    arcaneArcher: "arcane archer",
    battleMaster: "battle master",
    cavalier: "cavalier",
    champion: "champion",
    eldritchKnight: "eldritch knight",
    psiWarrior: "psi warrior",
    purpleDragonKnight: "purple dragon knight",
    runeKnight: "rune knight",
    samurai: "samurai",
  },
  monk: {
    ascendantDragon: "ascendant dragon",
    astralSelf: "astral self",
    drunkenMaster: "drunken master",
    fourElements: "four elements",
    kensei: "kensei",
    longDeath: "long death",
    mercy: "mercy",
    openHand: "open hand",
    shadow: "shadow",
    sunSoul: "sun soul",
  },
  paladin: {
    ancients: "ancients",
    conquest: "conquest",
    crown: "crown",
    devotion: "devotion",
    glory: "glory",
    oathbreaker: "oathbreaker",
    redemption: "redemption",
    vengeance: "vengeance",
    watchers: "watchers",
  },
  ranger: {
    beastMaster: "beast master",
    drakewarden: "drakewarden",
    feyWanderer: "fey wanderer",
    gloomStalker: "gloom stalker",
    horizonWalker: "horizon walker",
    hunter: "hunter",
    monsterSlayer: "monster slayer",
    swarmkeeper: "swarmkeeper",
  },
  rogue: {
    arcaneTrickster: "arcane trickster",
    assassin: "assassin",
    inquisitive: "inquisitive",
    mastermind: "mastermind",
    phantom: "phantom",
    scout: "scout",
    soulknife: "soulknife",
    swashbuckler: "swashbuckler",
    thief: "thief",
  },
  sorceror: {
    aberrantMind: "aberrant mind",
    clockworkSoul: "clockwork soul",
    divineSoul: "divine soul",
    draconicBloodline: "draconic bloodline",
    psionicSoul: "psionic soul",
    shadowSorcery: "shadow sorcery",
    stormSorcery: "storm sorcery",
    sorcerorWildMagic: "wild magic - sorcerer",
  },
  warlock: {
    archfey: "the archfey",
    celestial: "the celestial",
    fathomless: "the fathomless",
    fiend: "the fiend",
    genie: "the genie",
    greatOldOne: "the great old one",
    hexblade: "the hexblade",
    undead: "the undead",
    undying: "the undying",
  },
  wizard: {
    abjuration: "abjuration",
    bladesinging: "bladesinging",
    conjuration: "conjuration",
    divination: "divination",
    enchantment: "enchantment",
    evocation: "evocation",
    illusion: "illusion",
    necromancy: "necromancy",
    orderOfScribes: "order of scribes",
    psionics: "psionics",
    transmutation: "transmutation",
    warMagic: "war magic",
  }
}